---
title: "R Notebook"
output: html_document
---

## Mastering R Class 1: Final Quiz
```{r loadPackages message = FALSE, warning = FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(readxl)
```

## Question 1
```{r loadData1}
daily <- read_csv("daily_SPEC_2014.csv.bz2")
temp <- rename(daily, Arithmetic_Mean = 'Arithmetic Mean')
temp %>% filter(temp$'State Name' == "Wisconsin" &  temp$`Parameter Name` == "Bromine PM2.5 LC") %>% summarise(average=mean(Arithmetic_Mean))
```

## Ouestion 2
```{r}
daily %>%
   group_by(`Parameter Name`)%>%
   filter(`Parameter Name` %in% c("Sulfur PM2.5 LC","EC2 PM2.5 LC","OC CSN Unadjusted PM2.5 LC TOT","Sodium PM2.5 LC"))%>%
   summarize(avg= mean(`Arithmetic Mean`)) %>%
   arrange(desc(avg))
```

## Question 3
```{r}
daily %>%
  filter(`Parameter Name` == 'Sulfate PM2.5 LC') %>%
  group_by(`State Code`, `County Code`, `Site Num`) %>%
  summarize(avg= mean(`Arithmetic Mean`)) %>% arrange(desc(avg))
```

## Question 4
```{r}
daily %>%
  filter(`Parameter Name` == "EC PM2.5 LC TOR" & `State Name` %in% c("California", "Arizona")) %>%
  group_by(`State Name`) %>%
  summarize(avg= mean(`Arithmetic Mean`)) 
```

## Ouestion 5
```{r}
daily %>%
filter(`Longitude` < -100 & `Parameter Name` == "OC PM2.5 LC TOR") %>%
summarise(median = median(`Arithmetic Mean`)) 
```

## Question 6
```{r}
install.packages('readxl')

aqs <- read_xlsx("aqs_sites.xlsx")
aqs %>%
 group_by(`State Code`, `County Code`, `Site Number`) %>%
 filter(`Land Use` == "RESIDENTIAL" & `Location Setting` == "SUBURBAN")
```

## Question 7
```{r}
d7 <- daily
d7$`State Code` <- as.numeric(d7$`State Code`)
d7$`County Code` <- as.numeric(d7$`County Code`)
d7$`Site Num` <- as.numeric(d7$`Site Num`)
jd <- left_join(aqs, d7, by = c("State Code", "County Code", "Site Number" = "Site Num"))
fd <- jd %>% filter(`Land Use` == "RESIDENTIAL" & `Location Setting` == "SUBURBAN" & `Longitude.x` >= -100 & `Parameter Name`=="EC PM2.5 LC TOR")
summarise(fd, median = median(`Arithmetic Mean`, na.rm = T))
```

## Question 8
```{r}
library(lubridate)
fd <- jd %>% filter(`Land Use` == "COMMERCIAL" & `Parameter Name`=="Sulfate PM2.5 LC")
mutate(fd, month = month(`Date Local`)) %>%
 group_by(month) %>%
 summarize(data = mean(`Arithmetic Mean`)) %>%
 arrange(desc(data))
```

## Question 9
```{r}
fd <- jd %>% filter(`State Code` == 6, `County Code` == 65, `Site Number` == 8001 & `Parameter Name` %in% c("Sulfate PM2.5 LC", "Total Nitrate PM2.5 LC")) 

mutate(fd, year = year(`Date Local`), month = month(`Date Local`), day = day(`Date Local`)) %>%
 group_by(year, month, day, `Parameter Name`) %>%
 summarize(avg = mean(`Arithmetic Mean`)) %>%
 ungroup() %>%
 group_by(year, month, day) %>%
 summarize(sum = sum(avg)) %>%
 filter(sum > 10)
```

## Question 10
```{r}
fd <- jd %>%
 filter(`Parameter Name` %in% c("Sulfate PM2.5 LC", "Total Nitrate PM2.5 LC")) 

temp <- mutate(fd, year = year(`Date Local`), month = month(`Date Local`), day = day(`Date Local`)) %>%
 group_by(`State Code`, `County Code`, `Site Number`, year, month, day, `Parameter Name`) %>%
 summarize(avg = mean(`Arithmetic Mean`)) %>%
 ungroup()

spread(temp, key = `Parameter Name`, value = avg) %>%
 group_by(`State Code`, `County Code`, `Site Number`) %>%
 summarise(cor = cor(`Total Nitrate PM2.5 LC`,`Sulfate PM2.5 LC`)) %>%
 arrange(desc(cor))
```

